apiVersion: apps/v1
kind: Deployment
metadata:
        name: aes-encryption-deplyment
        labels:
                app: aes-encryption-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: aes-encryption-service
        template:
                metadata:
                        labels:
                                app: aes-encryption-service
                spec:
                        containers:
                        - name: aes-encryption-service
                          image: jakeevans17/aes-encryption-service
                          ports:
                          - containerPort: 3000
