apiVersion: apps/v1
kind: Deployment
metadata:
        name: role-deployment
        labels:
                app: role-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: role-service
        template:
                metadata:
                        labels:
                                app: role-service
                spec:
                        containers:
                        - name: role-service
                          image: jakeevans17/role-service
                          ports:
                          - containerPort: 3000
