apiVersion: apps/v1
kind: Deployment
metadata:
        name: group-deployment
        labels:
                app: group-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: group-service
        template:
                metadata:
                        labels:
                                app: group-service
                spec:
                        containers:
                        - name: group-service
                          image: jakeevans17/group-service
                          ports:
                          - containerPort: 3000
