apiVersion: apps/v1
kind: Deployment
metadata:
        name: account-deployment
        labels:
                app: account-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: account-service
        template:
                metadata:
                        labels:
                                app: account-service
                spec:
                        containers:
                        - name: account-service
                          image: jakeevans17/account-service
                          ports:
                          - containerPort: 3000
