apiVersion: apps/v1
kind: Deployment
metadata:
        name: session-token-deployment
        labels:
                app: session-token-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: session-token-service
        template:
                metadata:
                        labels:
                                app: session-token-service
                spec:
                        containers:
                        - name: session-token-service
                          image: jakeevans17/session-token-service
                          ports:
                          - containerPort: 3000
