apiVersion: v1
kind: Service
metadata:
        name: authentication-client-service
spec:
        selector:
                app: authentication-client-service
        ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
        type: ClusterIP
